### ISSUE TITLE
Cut off image

### ISSUE THREAD

**Issue by winters-brown** [jellyfin/jellyfin-ux#13]
Was looking at branding/SVG/banner-logo-solid.svg and noticed its cut off.

![image](https://user-images.githubusercontent.com/17482298/52074220-65b11f80-2557-11e9-82b5-332f0049ca36.png)

**Comment by DraZtiK** [comment]
Just the way its displayed here. looks fine in an image app.

**Comment by winters-brown** [comment]
Awesome Thanks!
