### ISSUE TITLE
Jellyfin for Kodi

### ISSUE THREAD

**Issue by cvium** [jellyfin/jellyfin-ux#14]
I need a couple of images for the Kodi add-on to replace the Emby images:

- https://github.com/jellyfin/jellyfin-kodi/blob/master/resources/skins/default/media/logo-white.png
- https://github.com/jellyfin/jellyfin-kodi/blob/master/resources/skins/default/media/emby-icon.png (256x256 or 512x512)
- https://github.com/jellyfin/jellyfin-kodi/blob/master/fanart.jpg

**Comment by nvllsvm** [comment]
@cvium - I'll get them to you in the next day.
