### ISSUE TITLE
A logo icon is needed for Android TV

### ISSUE THREAD

**Issue by grafixeyehero** [jellyfin/jellyfin-ux#18]
Requesting: A logo icon is needed for Android TV should be 512 x 512 px.

Related: https://github.com/jellyfin/jellyfin-androidtv/issues/34

**Comment by grafixeyehero** [comment]
@anthonylavado i open PR https://github.com/jellyfin/jellyfin-androidtv/pull/70 use the low resultion 144*144 must replace by  new one

**Comment by thornbill** [comment]
We had a 512x512 icon in the Android TV repo previously. It was removed during a cleanup of unused resources. You can restore it from git history. https://github.com/jellyfin/jellyfin-androidtv/blob/338cfec07299c315db372fb3094e84935fd752da/app/src/main/res/drawable/logoicon512.png
