### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by oddstr13** [jellyfin/jellyfin-ux#21]
This repository is currently licensed under GPL-2.0.

1. Is this intended?
2. How would this impact other projects including the Jellyfin logo?
3. Would it not make more sense with a [Creative Commons](https://creativecommons.org/choose/) license?

**Comment by joshuaboniface** [comment]
cc @nvllsvm @EraYaN 

I think CC BY-SA is fine, if you two agree then we can change it.

**Comment by nvllsvm** [comment]
Works with me.

**Comment by anthonylavado** [comment]
I also vote CC-BY-SA.

**Comment by EraYaN** [comment]
CC BY-SA works for me too.

**Comment by vitorsemeano** [comment]
+1 for CC BY-SA
