### ISSUE TITLE
Sharp corners on SVG logo

### ISSUE THREAD

**Issue by ferferga** [jellyfin/jellyfin-ux#39]
Corners in the SVG assets that are present in this repository are really sharp and awkward looking.

**Images (from icon-transparent)**

![image](https://user-images.githubusercontent.com/10274099/89431874-c454ec00-d740-11ea-9c4e-f1398e12bdd7.png)

![image](https://user-images.githubusercontent.com/10274099/89431928-d20a7180-d740-11ea-9efd-3941dcac48ef.png)

**Comment by EraYaN** [comment]
This seems to be a Chromium issue with rendering.
