### ISSUE TITLE
Clarify who has copyright

### ISSUE THREAD

**Issue by strugee** [jellyfin/jellyfin-ux#41]
I'm using the Jellyfin logo for [an integration](https://github.com/strugee/nuvola-app-jellyfin) I'm hacking up, and as part of that I of course need to attribute the logo. However, I'm having a bit of trouble figuring out who to attribute it to. https://github.com/jellyfin/jellyfin-ux/blob/master/CONTRIBUTORS.md seems to imply that there's only one contributor, but there are 9 contributors to the repository? I'm not sure who out of those 9 have made contributions that are copyrightable so it'd be nice to have this documented somewhere, either in-repo or on the Branding docs.

**Comment by joshuaboniface** [comment]
As far as I'm concerned, as long as you attribute the logo to the "Jellyfin Project" and link to this repo, that satisfies any copyright issues. The logo images were originally created by @nvllsvm with modifications by @sparky8251 and @EraYaN AFAIK, and little tweaks along the way. We never really tracked it beyond what's shown in the PRs of this repo, but we're not too concerned as long as users are acting in good faith as you appear to be. I'll leave it to those I pinged to comment further should they wish.

**Comment by strugee** [comment]
Fantastic. I'll just go ahead with that - if anyone has other requests it can always be fixed later :-)

Will close this in a few days if we don't hear from folks you pinged.

**Comment by EraYaN** [comment]
It's my name in the CONTRIBUTORS, since I made the original SVGs of the current logo based on @nvllsvm design ideas, and I don't think anyone has added themselves since.

**Comment by anthonylavado** [comment]
Closing as question has been addressed.
