### ISSUE TITLE
Issue with the TVmaze Plugin image

### ISSUE THREAD

**Issue by h1dden-da3m0n** [jellyfin/jellyfin-ux#48]
The TVmaze Plugin svg seems to be broken, unless I am missing someting, as well as its naming seems off.
* https://github.com/jellyfin/jellyfin-ux/blob/master/plugins/SVG/jellyfin-plugin-tvmazesvg.svg

Additionally the naming of the rendered png seems to accidentally have the svg extension includes.
* https://github.com/jellyfin/jellyfin-ux/blob/master/plugins/repository/jellyfin-plugin-tvmazesvg.png

**Comment by MrTimscampi** [comment]
It may be due to all the boolean operations and fiddling I had to do to get the logo done and with the correct gradient...

**Comment by h1dden-da3m0n** [comment]
Just checked out the repo and tried open it in Inkscape and it works fine ... wat
