### ISSUE TITLE
List Fonts and Palette in Readme

### ISSUE THREAD

**Issue by nZambi-** [jellyfin/jellyfin-ux#5]
I think it would be beneficial to have the Officially adopted Font(s) and color palette listed, either in the UX readme or in a separate Style Guide.  This should include UX Choices as they are made ie: Jellyfin is one word, capitalized. Primary and Secondary (if needed) Fonts and styles… etc…

**Comment by anthonylavado** [comment]
Hey there! We've got this in our new documentation, but you're right - we should add at least a link, if not more info here on the Readme. Look for this soon!

In the meanwhile: https://jellyfin.readthedocs.io/en/latest/developer-docs/branding-guide/

**Comment by nZambi-** [comment]
Hi Anthony... Yup, I found the info easily in the Branding Guide at readthedocs... Took very little time and everything I was looking for was there. But I did come here first ;) 
Adding a link in the Readme would be more than enough probably. 
Thanks (again) for your time.
