### ISSUE TITLE
Best Practice for Plugin Logos

### ISSUE THREAD

**Issue by Middlepepper** [jellyfin/jellyfin-ux#57]
Hi All,

I'm a bit lost on what the "Recommend" or "Best Practice" is for the Jellyfin Plugin logos.

It looks like Plugin are referring to [repo.jellyfin.org](https://repo.jellyfin.org/releases/plugin/images/) to get images in most cases but it has not been updated since 2021.

Is anyone able to advise what the best way currently? Linking to this Github repo or the local plugin repo?

Thank for everyone help on this project.

**Comment by nielsvanvelzen** [comment]
We've updated the images at repo.jellyfin.org now (needs to be done manually). We host all images for our official plugins at repo.jellyfin.org, third-party plugins often link to raw.githubusercontent.com.

**Comment by Middlepepper** [comment]
Thanks niel, so just to confirm.

The official/recommended way is to link to plugin images on [repo.jellyfin.org](https://repo.jellyfin.org/releases/plugin/images/) which it is manually synced.
People can still link to the raw.githubusercontent.com here rather than their personal repos as second preference.
And we can always include it locally using the image.png or image:"" in the build yaml as a back up.

**Comment by nielsvanvelzen** [comment]
The plugin manifest is JSON, not YAML. The imageUrl in it should refer to a https link.

**Comment by nielsvanvelzen** [comment]
Closing as solved
